http:
  routers:
    api:
      rule: "Host(`api.finanns.space`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: api

    frontend:
      rule: "Host(`finanns.space`) || Host(`www.finanns.space`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: frontend

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:8082"

    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
